# Generated by Django 2.0 on 2017-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='foam',
            field=models.BooleanField(default=True),
        ),
    ]
