# Generated by Django 2.0 on 2017-12-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffee', '0002_auto_20171207_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
